### ISSUE TITLE
Drawing tools stuck after single click

### ISSUE THREAD

**Issue by sinamcr7** [annotorious/annotorious-openseadragon#186]
Hi
I'm using annotorious-openseadragon and annotorious-selector-pack to annotate my WSI images but when using any tool other than the point tool if I single click and don't drag and drop while holding shift that tool gets stuck and just pans, so it won't work until I refresh page or use point tool and go back to desired drawing tool, its a temporary fix and the bug is so annoying, please if someone has any fixes for this help me. here's how it happens:
![bug gif](https://github.com/annotorious/annotorious-openseadragon/assets/17440609/9bb4ceb7-dd12-4305-a60d-503c9248ebbf)

**Comment by rsimon** [comment]
Look like the last commit (https://github.com/annotorious/annotorious-openseadragon/commit/ffc98263c8cdc4c091583e09ae1eb304841d42c7) has fixed this. I published a new release (2.7.14).

**Comment by sinamcr7** [comment]
thanks alot

**Comment by blms** [comment]
I think I'm still experiencing a version of this with the polygon tool. It can be observed on the [example page here](https://annotorious.github.io/getting-started/osd-plugin/):

- Choose the polygon tool
- Shift and click on a single point on the page
- Without releasing shift, try to shift and drag—it will only pan the image, not draw

Something similar happens when you press `Escape` while in the middle of drawing a polygon. I suspect both have something to do with the polygon's `stop()` function, so maybe it warrants a new issue?
